### ISSUE TITLE
ModuleNotFoundError: No module named 'user_xsh'

### ISSUE THREAD

**Issue by giladreti** [jnoortheen/xontrib-powerline3#3]
powerline3 is not able to load on my fresh new installed xonsh. It fails with the following traceback:

```
Traceback (most recent call last):
  File "/usr/bin/xonsh/lib/python3.8/site-packages/xonsh/xontribs.py", line 89, in xontribs_load
    update_context(name, ctx=ctx)
  File "/usr/bin/xonsh/lib/python3.8/site-packages/xonsh/xontribs.py", line 72, in update_context
    modctx = xontrib_context(name)
  File "/usr/bin/xonsh/lib/python3.8/site-packages/xonsh/xontribs.py", line 37, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/bin/xonsh/lib/python3.8/site-packages/xontrib/powerline3.py", line 1, in <module>
    import xontrib_powerline3.processor
  File "/usr/bin/xonsh/lib/python3.8/site-packages/xontrib_powerline3/processor.py", line 8, in <module>
    from user_xsh.utils import logger
ModuleNotFoundError: No module named 'user_xsh'
```

As far as I can tell, the "user_xsh" is used only for importing the logger, which is unused.

**Comment by jnoortheen** [comment]
it is some debugging code leaking into source. I just pushed a fix.
